version: '3'

services:
  rocketchat_one:
    container_name: rocketchat_one
    image: rocket.chat:6.13.1
    command: >
      bash -c
        "for i in `seq 1 30`; do
          node main.js &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - stack.env
    environment:
      - PORT=3000
    ports:
      - 3000:3000
